import * as React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import BasicCard from '../components/Card'
import TemporaryDrawer from '../components/SideDrawer'
import Button from '@mui/material/Button';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [menuOpen, setMenuOpen] = React.useState(true)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       Henlo, this is the NEXT page! Plus your routing works! YAY

       <Link href="/">Home</Link>
       <BasicCard />
       <TemporaryDrawer menuOpen={menuOpen}/>
       <Button variant="contained" onClick={()=> {setMenuOpen(!menuOpen)}}>Menu</Button>
      </main>
    </>
  )
}
